# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:35
from __future__ import unicode_literals

import Landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fb', models.CharField(max_length=500)),
                ('git', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to=Landing.models.UploadToPathAndRename('/media/ayman/Data1/Projects/FabLab/MD/Local/dev/MDWebsite/Landing/media/upload'))),
            ],
        ),
    ]
