# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='at',
            field=models.CharField(default='', max_length=200),
        ),
    ]
